#!/usr/bin/env python

import fileinput

from tact import aphorism
from tact import sentence


for line in fileinput.input():
    line = line.strip()

    for s in sentence.do_punkt(line):
        if not s:
            continue

        if not aphorism.is_aphorism(s):
            continue

        print s.encode("utf-8")
